import 'package:flutter/material.dart';

class AppModel {
  final String name, image, description, category;
  final double rating;
  final int review, price;
  List<Color> fcolor;
  List<String> size;
  bool isCheck;

  AppModel({
    required this.name,
    required this.image,
    required this.description,
    required this.category,
    required this.rating,
    required this.review,
    required this.price,
    required this.fcolor,
    required this.size,
    required this.isCheck,
  });
}

List<AppModel> fashionEcommerceApp = [
  AppModel(
      name: "Oversized Fit Printed Mesh T-Shirt",
      rating: 4.9,
      image: "assets/category_image/image23.png",
      price: 295,
      review: 136,
      isCheck: true,
      category: "Women",
      fcolor: [Colors.black, Colors.blue, Colors.blue[100]!],
      size: ["XS", "S", "M"],
      description: "Stylish and comfortable denim jacket for everyday wear 1"),
  AppModel(
      name: "Printed Sweatshirt",
      rating: 4.8,
      image: "assets/category_image/image24.png",
      price: 314,
      review: 178,
      isCheck: false,
      category: "Women",
      fcolor: [Colors.green, Colors.black, Colors.blue[100]!],
      size: ["XS", "S", "M"],
      description: "Stylish and comfortable denim jacket for everyday wear 2"),
  AppModel(
      name: "Classic Denim Jacket",
      rating: 4.7,
      image: "assets/category_image/image25.png",
      price: 420,
      review: 210,
      isCheck: false,
      category: "Men",
      fcolor: [Colors.blue, Colors.black, Colors.grey],
      size: ["XS", "S", "M"],
      description: ""),
  AppModel(
      name: "Slim Fit Chinos",
      rating: 4.6,
      image: "assets/category_image/image26.png",
      price: 340,
      review: 190,
      isCheck: true,
      category: "Men",
      fcolor: [Colors.brown, Colors.black, Colors.green],
      size: ["XS", "S", "M"],
      description: ""),
  AppModel(
      name: "Casual Cotton Shirt",
      rating: 4.8,
      image: "assets/category_image/image27.png",
      price: 280,
      review: 150,
      isCheck: false,
      category: "Men",
      fcolor: [Colors.white, Colors.lightBlue, Colors.blue],
      size: ["XS", "S", "M"],
      description: ""),
  AppModel(
      name: "Floral Print Dress",
      rating: 4.9,
      image: "assets/category_image/image28.png",
      price: 360,
      review: 220,
      isCheck: true,
      category: "Women",
      fcolor: [Colors.red, Colors.pink, Colors.orange],
      size: ["XS", "S", "M"],
      description: ""),
  // AppModel(
  //     name: "Running Sneakers",
  //     rating: 4.7,
  //     image: "assets/category_image/image29.png",
  //     price: 500,
  //     review: 275,
  //     isCheck: false,
  //     category: "Unisex",
  //     fcolor: [Colors.white, Colors.grey, Colors.black],
  //     size: ["XS", "S", "M"],
  //     description: ""),
  // AppModel(
  //     name: "Leather Handbag",
  //     rating: 4.8,
  //     image: "assets/category_image/image30.png",
  //     price: 650,
  //     review: 180,
  //     isCheck: true,
  //     category: "Women",
  //     fcolor: [Colors.brown, Colors.black, Colors.grey],
  //     size: ["XS", "S", "M"],
  //     description: ""),
  // AppModel(
  //     name: "Sports Watch",
  //     rating: 4.9,
  //     image: "assets/category_image/image31.png",
  //     price: 750,
  //     review: 300,
  //     isCheck: false,
  //     category: "Unisex",
  //     fcolor: [Colors.black, Colors.blue, Colors.white],
  //     size: ["XS", "S", "M"],
  //     description: ""),
  // AppModel(
  //     name: "Leather Boots",
  //     rating: 4.7,
  //     image: "assets/category_image/image32.png",
  //     price: 800,
  //     review: 250,
  //     isCheck: true,
  //     category: "Men",
  //     fcolor: [Colors.brown, Colors.black, Colors.grey],
  //     size: ["XS", "S", "M"],
  //     description: ""),
  // AppModel(
  //     name: "Knitted Scarf",
  //     rating: 4.6,
  //     image: "assets/category_image/image33.png",
  //     price: 120,
  //     review: 100,
  //     isCheck: false,
  //     category: "Unisex",
  //     fcolor: [Colors.grey, Colors.blue, Colors.black],
  //     size: ["XS", "S", "M"],
  //     description: ""),
  // AppModel(
  //     name: "Aviator Sunglasses",
  //     rating: 4.9,
  //     image: "assets/category_image/image34.png",
  //     price: 450,
  //     review: 190,
  //     isCheck: true,
  //     category: "Unisex",
  //     fcolor: [Colors.black, Colors.brown, Colors.white],
  //     size: ["XS", "S", "M"],
  //     description: ""),
  // AppModel(
  //     name: "Winter Coat",
  //     rating: 4.8,
  //     image: "assets/category_image/image35.png",
  //     price: 900,
  //     review: 320,
  //     isCheck: false,
  //     category: "Women",
  //     fcolor: [Colors.black, Colors.grey, Colors.white],
  //     size: ["XS", "S", "M"],
  //     description: ""),
  // AppModel(
  //     name: "Bomber Jacket",
  //     rating: 4.7,
  //     image: "assets/category_image/image36.png",
  //     price: 550,
  //     review: 180,
  //     isCheck: true,
  //     category: "Men",
  //     fcolor: [Colors.green, Colors.black, Colors.red],
  //     size: ["XS", "S", "M"],
  //     description: ""),
  // AppModel(
  //     name: "Slim Fit Jeans",
  //     rating: 4.8,
  //     image: "assets/category_image/image37.png",
  //     price: 320,
  //     review: 250,
  //     isCheck: false,
  //     category: "Women",
  //     fcolor: [Colors.blue, Colors.black, Colors.white],
  //     size: ["XS", "S", "M"],
  //     description: ""),
  // AppModel(
  //     name: "Trendy Sneakers",
  //     rating: 4.6,
  //     image: "assets/category_image/image38.png",
  //     price: 480,
  //     review: 210,
  //     isCheck: true,
  //     category: "Unisex",
  //     fcolor: [Colors.white, Colors.red, Colors.black],
  //     size: ["XS", "S", "M"],
  //     description: ""),
  // AppModel(
  //     name: "Floral Romper",
  //     rating: 4.9,
  //     image: "assets/category_image/image39.png",
  //     price: 420,
  //     review: 220,
  //     isCheck: false,
  //     category: "Women",
  //     fcolor: [Colors.orange, Colors.pink, Colors.yellow],
  //     size: ["XS", "S", "M"],
  //     description: ""),
  // AppModel(
  //     name: "Leather Jacket",
  //     rating: 4.8,
  //     image: "assets/category_image/image40.png",
  //     price: 950,
  //     review: 310,
  //     isCheck: true,
  //     category: "Men",
  //     fcolor: [Colors.black, Colors.brown, Colors.white],
  //     size: ["XS", "S", "M"],
  //     description: ""),
  // AppModel(
  //     name: "Knitted Sweater",
  //     rating: 4.7,
  //     image: "assets/category_image/image41.png",
  //     price: 400,
  //     review: 150,
  //     isCheck: false,
  //     category: "Women",
  //     fcolor: [Colors.white, Colors.green, Colors.grey],
  //     size: ["XS", "S", "M"],
  //     description: ""),
  // AppModel(
  //     name: "Chukka Boots",
  //     rating: 4.8,
  //     image: "assets/category_image/image42.png",
  //     price: 530,
  //     review: 240,
  //     isCheck: true,
  //     category: "Men",
  //     fcolor: [Colors.brown, Colors.black, Colors.blue],
  //     size: ["XS", "S", "M"],
  //     description: "")
];
 

//  const myDescription1 = "Elevate your Casual wardrobe With our";
//    const myDescription2 = "Elevate your Casual wardrobe With our..........";